### ISSUE TITLE
라이센스 정책

### ISSUE THREAD

**Issue by hyunjik-song** [MrBananaHuman/KorGPT2PretraingTutorial#5]
안녕하세요. 공개해주신 코드들이 큰 도움이 되고 있습니다. 혹시 라이센스 정책이 어떻게 되는지요?

**Comment by MrBananaHuman** [comment]
네 안녕하세요~ 정책은 자유롭게 사용해주셔도 괜찮습니다만, 반드시 출처 링크는 남겨주세요~
